---
- name: Switching off  VM hosts Target01 and Target02
  hosts: localhost
  tasks:
  - name: Powering down Target01
    shell:
      cmd: vagrant halt
      chdir: ~/Vagrant/Ubuntu01
  
  - name: Powering down Target02
    shell:
      cmd: vagrant halt
      chdir: ~/Vagrant/Ubuntu02
        
